[build]
  command = "CI= npm run build \"GENERATE_SOURCEMAP\" = false"
  publish = "build"

[build.environment]
  GENERATE_SOURCEMAP = "true"

[build.production.environment]
  GENERATE_SOURCEMAP = "false"